### ISSUE TITLE
Is there any example calling stored procedure by passing parameter?

### ISSUE THREAD

**Issue by namjitharavind** [underscoreio/essential-slick-code#16]
I am struggling to to see one example calling stored procedure. Please help

**Comment by d6y** [comment]
@namjitharavind  nothing as yet, but I started exploring the area. There might be something in this example that helps: https://github.com/d6y/slick-postgresql-stored-proc

**Comment by d6y** [comment]
Closing as I've moved this ticket to the main book text repository: https://github.com/underscoreio/essential-slick/issues/159
